config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  
  resources :books do
    resource :favorites, only:[:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end
  
  post 'books/:id', to: 'books#create'
  resources :users, only: [:index, :show, :edit, :update]
  
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :title, presence: true
  validates :body, presence: true, length: {minimum: 1, maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @books = Book.all
    if @book.save
      redirect_to book_path(@book), flash: { notice: 'Book was successfully created.'}
    else
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @new_book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @user = @book.user
  end
  
  def edit
    @book = Book.find(params[:id])
    if current_user != @book.user
      redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), flash: { notice: 'Book was successfully changed.'}
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<%if @book.errors.any? %>
  <%= @book.errors.count %>errors caused:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<h1>Editing Book</h1>

<%= form_for(@book) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, id: :book_body %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to "Show", @book %> |
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<div id="error_explanation">
  <%if @book.errors.any? %>
    <%= @book.errors.count %>errors caused:
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
</div>


<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/sidebar', user: current_user, new_book: @new_book %>
    
    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to attachment_image_tag(book.user, :profile_image, fallback: "no_image.jpg", size: "60x60"), user_path(book.user.id) %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td><%= link_to "#{book.book_comments.count} Comment", book_path(book.id) %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book), {method: :delete, class: "fa fa-heart", style: "color:magenta"} do %>
                      <%= book.favorites.count %> 
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), {method: :post, class: "fa fa-heart"} do %>
                      <%= book.favorites.count %> 
                    <% end %>
                  </p>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
  

app/views/books/new.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors caused:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<h1>投稿フォーム</h1>

<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <%= notice %>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/sidebar', user: @book.user, new_book: @new_book %>
    
    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class='table table-hover table-inverse'>
        <tbody>
          <tr>
            <td><%= attachment_image_tag @book.user, :profile_image, fallback: "no_image.jpg", size: "60x60" %>
            <br><%= link_to @book.user.name, user_path(@book.user.id) %></td>
            <td><%= link_to @book.title, book_path(@book.id) %></td>
            <td><%= @book.body %></td>
          </tr>
        </tbody>
      </table>
      
      <div>
        <% if current_user == @book.user%>
          <%= link_to "Edit", edit_book_path(@book) %> | 
          <%= link_to "Destroy", book_path(@book), method: :delete %>
        <% end %>
      </div>
      
      
      <div>
        <% if @book.favorited_by?(current_user) %>
        <p>
          <%= link_to book_favorites_path(@book), {method: :delete, class: "fa fa-heart", style: "color:magenta"} do %>
            <%= @book.favorites.count %>
          <% end %>
        </p>
        <% else %>
        <p>
          <%= link_to book_favorites_path(@book), {method: :post, class: "fa fa-heart"} do %>
            <%= @book.favorites.count %>
          <% end %>
        </p>
      <% end %>
      </div>
      
      
      
      <div>
        <p>コメント件数: <%= @book.book_comments.count %></p>
        <% @book.book_comments.each do |comment| %>
          <%= attachment_image_tag comment.user, :profile_image, fallback: "no_image.jpg", size: "60x60" %>
          <%= comment.user.name %>
          <%= comment.comment %>
          
          <% if current_user == comment.user%>
            <%= link_to "Destroy", book_book_comment_path(book_id: @book.id, id: comment.id), method: :delete %>
          <% end %>
        <% end %>
      </div>
      
      <div>
        <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
          <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
          <%= f.submit "送信する" %>
        <% end %>
      </div>
    </div>
  </div>
</div>